services:
  postgresql:
    image: postgres:14-alpine
    env_file: ".env"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresql-local:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgresql-local: